export type ReferenceSign = { name: string; image: string };
export type ReferenceGroup = { title: string; items: ReferenceSign[] };
export const referenceGroups: ReferenceGroup[] = [
  { title: "علامات الخطر", items: [
    { name: "خطر منعرج لليمين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p1_1.png" },
    { name: "خطر منعرج لليسار", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p1_0.png" },
    { name: "منعرجات متتابعة أولها على اليسار", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p1_2.png" },
    { name: "منعرجات متتابعة أولها على اليمين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p1_3.png" },
    { name: "خطر منحدر حاد 6%", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p1_4.png" },
    { name: "منحدر خطير بنسبة 10%", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p1_5.png" },
    { name: "خطر طريق ضيق من جهة اليمين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_0.png" },
    { name: "خطر طريق ضيق من الجهتين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_1.png" },
    { name: "خطر طريق ضيق محليا", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_2.png" },
    { name: "خطر طريق ضيق من جهة اليسار", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_3.png" },
    { name: "خطر منفذ إلى رصيف أو ضفة نهر", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_4.png" },
    { name: "خطر جسر متحرك", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_5.png" },
    { name: "خطر مخفض السرعة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_6.png" },
    { name: "خطر طريق محدب أو وهدة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_7.png" },
    { name: "خطر طريق تغمرها المياه", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_8.png" },
    { name: "خطر طريق زلقة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_9.png" },
    { name: "خطر تساقط الأحجار", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_10.png" },
    { name: "خطر تطاير الحصى", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p2_11.png" },
    { name: "انتباه مكان يرتاده الأطفال", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_0.png" },
    { name: "خطر ممر الراجلين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_1.png" },
    { name: "خطر مرور حيوانات أليفة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_2.png" },
    { name: "خطر مرور الدراجات", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_3.png" },
    { name: "خطر مرور الجمال", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_4.png" },
    { name: "خطر مرور حيوانات أليفة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_5.png" },
    { name: "خطر مرور الفرسان", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_6.png" },
    { name: "خطر مرور حيوانات برية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_7.png" },
    { name: "خطر مرور طائرات على علو منخفض", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_8.png" },
    { name: "انتباه أضواء المرور الثلاثية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p3_9.png" },
    { name: "خطر السير في الاتجاهين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_0.png" },
    { name: "خطر رياح جانبية قوية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_1.png" },
    { name: "سكة حديدية بحواجز", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_2.png" },
    { name: "انتباه أخطار متنوعة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_3.png" },
    { name: "خطر سكة حديدية بدون حواجز", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_4.png" },
    { name: "خطر مرور الترامواي", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_5.png" },
    { name: "خطر مرور جرارات فلاحية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_6.png" },
    { name: "خطر مرور عربات مجرورة بالحيوانات", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_7.png" },
    { name: "خطر طريق محدب أو وهدة مؤقت", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_8.png" },
    { name: "خطر طريق ضيق من الجهتين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p4_9.png" },
    { name: "خطر مؤقت: طريق تضيق من جهة اليمين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_0.png" },
    { name: "خطر مؤقت: طريق تضيق من جهة اليسار", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_1.png" },
    { name: "خطر طريق زلقة مؤقت", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_2.png" },
    { name: "خطر أشغال مؤقتة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_3.png" },
    { name: "انتباه أخطار متنوعة مؤقتة", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_4.png" },
    { name: "إعلان مؤقت عن إشارات ضوئية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_5.png" },
    { name: "خطر مؤقت: تطاير الحصى", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_6.png" },
    { name: "خطر مؤقت: حادثة سير", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_7.png" },
    { name: "خطر مؤقت: ازدحام مروري", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p5_8.png" },
  ] },
  { title: "علامات ملتقى الطرق والأسبقية", items: [
    { name: "نهاية طريق ذات أولوية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p7_1.png" },
    { name: "طريق ذات أولوية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p7_0.png" },
    { name: "ملتقى طرق مع أولوية المرور", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_6.png" },
    { name: "انتباه ملتقى طرقي دوراني", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_7.png" },
    { name: "ملتقى طرق الأسبقية لليمين", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_5.png" },
    { name: "إشارة متقدمة لعلامة قف على بعد 150 متر", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_4.png" },
    { name: "إعطاء حق الأسبقية على بعد 150 متر", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_3.png" },
    { name: "إعطاء حق الأسبقية", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_2.png" },
    { name: "علامة قف", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_1.png" },
    { name: "علامة قف", image: "https://assets.conduire.ma/signs/khatar-asba9ia/sign_p6_0.png" },
  ] },
  { title: "لوحات متعلقة بالفئات", items: [
    { name: "لوحة إضافية لمركبات النقل الجماعي", image: "https://assets.conduire.ma/signs/louihat/sign_p3_0.png" },
    { name: "لوحة تكميلية للسيارات الخفيفة", image: "https://assets.conduire.ma/signs/louihat/sign_p2_3.png" },
    { name: "مركز إغاثة وهاتف استغاثة ومطفأة حريق", image: "https://assets.conduire.ma/signs/louihat/sign_p1_2.png" },
    { name: "ممنوع من 1 إلى 15 من الشهر", image: "https://assets.conduire.ma/signs/louihat/sign_p1_3.png" },
    { name: "لوحة إضافية قف على بعد 150 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p1_4.png" },
    { name: "لوحة تكميلية لمركبات نقل البضائع الخطيرة", image: "https://assets.conduire.ma/signs/louihat/sign_p1_5.png" },
    { name: "لوحة إضافية للاتجاه نحو اليمين", image: "https://assets.conduire.ma/signs/louihat/sign_p1_6.png" },
    { name: "لوحة تكميلية للاتجاه نحو اليسار", image: "https://assets.conduire.ma/signs/louihat/sign_p1_7.png" },
    { name: "لوحة تكميلية للدراجات", image: "https://assets.conduire.ma/signs/louihat/sign_p1_8.png" },
    { name: "لوحة هاتف الإغاثة", image: "https://assets.conduire.ma/signs/louihat/sign_p1_9.png" },
    { name: "لوحة إضافية للوزن 5.5 طن", image: "https://assets.conduire.ma/signs/louihat/sign_p1_10.png" },
    { name: "علامة إضافية لمسافة الامتداد 50 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p1_11.png" },
    { name: "لوحة تكميلية للاتجاه نحو الأسفل", image: "https://assets.conduire.ma/signs/louihat/sign_p1_12.png" },
    { name: "لوحة تكميلية لسلاسل الثلج", image: "https://assets.conduire.ma/signs/louihat/sign_p1_13.png" },
    { name: "لوحة شكل ملتقى الطرق", image: "https://assets.conduire.ma/signs/louihat/sign_p1_14.png" },
    { name: "خطر الانهيار الثلجي", image: "https://assets.conduire.ma/signs/louihat/sign_p1_15.png" },
    { name: "لوحة تكميلية للامتداد", image: "https://assets.conduire.ma/signs/louihat/sign_p1_16.png" },
    { name: "مركبات يتجاوز طولها 10 أمتار", image: "https://assets.conduire.ma/signs/louihat/sign_p1_17.png" },
    { name: "لوحة إضافية لمسافة الأمان في المنحدر", image: "https://assets.conduire.ma/signs/louihat/sign_p1_18.png" },
    { name: "لوحة تكميلية للوزن على المحور 5 طن", image: "https://assets.conduire.ma/signs/louihat/sign_p1_19.png" },
    { name: "لوحة إضافية للاتجاه نحو اليسار", image: "https://assets.conduire.ma/signs/louihat/sign_p1_20.png" },
    { name: "لوحة إضافية خاصة بالدراجات النارية الصغيرة", image: "https://assets.conduire.ma/signs/louihat/sign_p1_21.png" },
  ] },
  { title: "لوحات مكملة لعلامات الوقوف والتوقف", items: [
    { name: "اترك الأسبقية", image: "https://assets.conduire.ma/signs/louihat/sign_p2_0.png" },
    { name: "ممنوع من 1 إلى 15 من الشهر", image: "https://assets.conduire.ma/signs/louihat/sign_p1_3.png" },
    { name: "لوحة تكميلية للامتداد 15 كلم", image: "https://assets.conduire.ma/signs/louihat/sign_p2_4.png" },
    { name: "لوحة تكميلية باستثناء ذوي الاحتياجات الخاصة", image: "https://assets.conduire.ma/signs/louihat/sign_p2_5.png" },
    { name: "مخرج معمل", image: "https://assets.conduire.ma/signs/louihat/sign_p2_6.png" },
  ] },
  { title: "لوحات مسافة", items: [
    { name: "لوحة إضافية خاصة بالحافلات", image: "https://assets.conduire.ma/signs/louihat/sign_p3_0.png" },
  ] },
  { title: "لوحات امتداد", items: [
    { name: "لوحة إضافية للمسافة 1000 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p4_0.png" },
  ] },
  { title: "لوحات الوقوف والأسبقية", items: [
    { name: "لوحة تكميلية للمنع حسب الأوقات", image: "https://assets.conduire.ma/signs/louihat/sign_p5_0.png" },
    { name: "لوحة إضافية للمسافة 150 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p5_1.png" },
  ] },
  { title: "لوحات التموقع واالتجاهات", items: [
    { name: "لوحة تكميلية للامتداد 1000 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p6_0.png" },
    { name: "لوحة تكميلية للمواد المتفجرة", image: "https://assets.conduire.ma/signs/louihat/sign_p6_2.png" },
    { name: "لوحة تكميلية لمخطط الطريق", image: "https://assets.conduire.ma/signs/louihat/sign_p6_3.png" },
  ] },
  { title: "لوحات خاصة بتطبيق تعليمات الوقوف و التوقف", items: [
    { name: "لوحة إضافية لمحطة الوزن", image: "https://assets.conduire.ma/signs/louihat/sign_p7_0.png" },
    { name: "لويحة تكميلية للمسافة والاتجاه يسارا 50 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p7_4.png" },
    { name: "لوحة إضافية للدراجات النارية", image: "https://assets.conduire.ma/signs/louihat/sign_p7_5.png" },
  ] },
  { title: "إرشادات مختلفة", items: [
    { name: "موقف سيارات بالأداء", image: "https://assets.conduire.ma/signs/louihat/sign_p8_0.png" },
    { name: "لوحة إضافية للراجلين", image: "https://assets.conduire.ma/signs/louihat/sign_p8_4.png" },
    { name: "لوحة تكميلية للاتجاه نحو اليسار", image: "https://assets.conduire.ma/signs/louihat/sign_p8_5.png" },
    { name: "لوحة تكميلية للمسافة والاتجاه 50 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p8_6.png" },
    { name: "لوحة تكميلية لعرض العربة 2 متر", image: "https://assets.conduire.ma/signs/louihat/sign_p8_7.png" },
    { name: "قارعة طريق مشوهة", image: "https://assets.conduire.ma/signs/louihat/sign_p8_8.png" },
  ] },
  { title: "لوحات متعلقة بالرسوم البيانية لملتقى الطرق", items: [
    { name: "لوحة إضافية للعربات المجرورة بالحيوانات", image: "https://assets.conduire.ma/signs/louihat/sign_p9_0.png" },
    { name: "لوحة إضافية للجرارات الفلاحية", image: "https://assets.conduire.ma/signs/louihat/sign_p9_2.png" },
  ] },
  { title: "علامات المنع", items: [
    { name: "ممنوع مرور الحافلات", image: "https://assets.conduire.ma/signs/alman3/sign_p1_0.png" },
    { name: "ممنوع القيام بنصف دورة", image: "https://assets.conduire.ma/signs/alman3/sign_p1_1.png" },
    { name: "ممنوع مرور العربات المجرورة بالحيوانات", image: "https://assets.conduire.ma/signs/alman3/sign_p1_2.png" },
    { name: "ممنوع مرور الدراجات النارية", image: "https://assets.conduire.ma/signs/alman3/sign_p1_3.png" },
    { name: "ممنوع مرور المركبات التي يتجاوز علوها 4.5 متر", image: "https://assets.conduire.ma/signs/alman3/sign_p1_4.png" },
    { name: "ممنوع مرور العربات التي يتجاوز عرضها 2.5 متر", image: "https://assets.conduire.ma/signs/alman3/sign_p1_5.png" },
    { name: "ممنوع مرور العربات ذات المحرك", image: "https://assets.conduire.ma/signs/alman3/sign_p1_6.png" },
    { name: "ممنوع مرور العربات اليدوية", image: "https://assets.conduire.ma/signs/alman3/sign_p1_7.png" },
    { name: "ممنوع مرور العربات التي تحمل مواد ملوثة للمياه", image: "https://assets.conduire.ma/signs/alman3/sign_p1_8.png" },
    { name: "ممنوع مرور العربات التي تحمل مواد خطيرة", image: "https://assets.conduire.ma/signs/alman3/sign_p1_9.png" },
    { name: "ممنوع مرور العربات التي يتجاوز وزنها 5.5 طن", image: "https://assets.conduire.ma/signs/alman3/sign_p1_10.png" },
    { name: "ممنوع مرور السيارات الخفيفة", image: "https://assets.conduire.ma/signs/alman3/sign_p1_11.png" },
    { name: "تحديد السرعة في 120 كلم/س", image: "https://assets.conduire.ma/signs/alman3/sign_p1_12.png" },
    { name: "قف - الدرك الملكي", image: "https://assets.conduire.ma/signs/alman3/sign_p1_13.png" },
    { name: "ممنوع مرور الجرارات والآليات الفلاحية", image: "https://assets.conduire.ma/signs/alman3/sign_p1_14.png" },
    { name: "تحديد السرعة في 80 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_15.png" },
    { name: "ممنوع تغيير الاتجاه نحو اليمين", image: "https://assets.conduire.ma/signs/alman3/sign_p1_16.png" },
    { name: "ممنوع مرور المركبات التي تحمل مواد متفجرة", image: "https://assets.conduire.ma/signs/alman3/sign_p1_17.png" },
    { name: "تحديد السرعة في 20 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_18.png" },
    { name: "أسبقية المرور للاتجاه المقابل", image: "https://assets.conduire.ma/signs/alman3/sign_p1_19.png" },
    { name: "ممنوع استعمال المنبه الصوتي", image: "https://assets.conduire.ma/signs/alman3/sign_p1_20.png" },
    { name: "تحديد السرعة في 60 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_21.png" },
    { name: "ممنوع مرور الدراجات النارية الخفيفة", image: "https://assets.conduire.ma/signs/alman3/sign_p1_22.png" },
    { name: "ممنوع ترك مسافة أقل من 70 متر", image: "https://assets.conduire.ma/signs/alman3/sign_p1_23.png" },
    { name: "ممنوع التجاوز على الشاحنات", image: "https://assets.conduire.ma/signs/alman3/sign_p1_24.png" },
    { name: "تحديد السرعة في 30 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_25.png" },
    { name: "ممنوع مرور المركبات التي يتجاوز طولها 10 أمتار", image: "https://assets.conduire.ma/signs/alman3/sign_p1_26.png" },
    { name: "ممنوع مرور الراجلين", image: "https://assets.conduire.ma/signs/alman3/sign_p1_27.png" },
    { name: "الجمارك", image: "https://assets.conduire.ma/signs/alman3/sign_p1_28.png" },
    { name: "قف عند محطة الأداء", image: "https://assets.conduire.ma/signs/alman3/sign_p1_29.png" },
    { name: "ممنوع التجاوز على السيارات", image: "https://assets.conduire.ma/signs/alman3/sign_p1_30.png" },
    { name: "ممنوع التوقف والوقوف", image: "https://assets.conduire.ma/signs/alman3/sign_p1_31.png" },
    { name: "ممنوع مرور المقطورات السياحية", image: "https://assets.conduire.ma/signs/alman3/sign_p1_32.png" },
    { name: "منع المرور على المركبات التي يتجاوز وزنها 2 طن لكل محور", image: "https://assets.conduire.ma/signs/alman3/sign_p1_33.png" },
    { name: "ممنوع الوقوف من 1 إلى 15 في الشهر", image: "https://assets.conduire.ma/signs/alman3/sign_p1_34.png" },
    { name: "ممنوع الوقوف", image: "https://assets.conduire.ma/signs/alman3/sign_p1_35.png" },
    { name: "ممنوع الوقوف مع الأداء", image: "https://assets.conduire.ma/signs/alman3/sign_p1_36.png" },
    { name: "تحديد السرعة في 100 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_37.png" },
    { name: "منطقة يمنع فيها الوقوف", image: "https://assets.conduire.ma/signs/alman3/sign_p1_38.png" },
    { name: "نهاية تحديد السرعة في 20 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_39.png" },
    { name: "الوقوف عند حاجز المراقبة الطرقية", image: "https://assets.conduire.ma/signs/alman3/sign_p1_40.png" },
    { name: "نهاية تحديد السرعة في 100 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_41.png" },
    { name: "نهاية منع التجاوز", image: "https://assets.conduire.ma/signs/alman3/sign_p1_42.png" },
    { name: "حاجز الثلج", image: "https://assets.conduire.ma/signs/alman3/sign_p1_43.png" },
    { name: "ممنوع المرور في هذا الاتجاه", image: "https://assets.conduire.ma/signs/alman3/sign_p1_44.png" },
    { name: "نهاية منع التجاوز على الشاحنات", image: "https://assets.conduire.ma/signs/alman3/sign_p1_45.png" },
    { name: "ممنوع الوقوف بالتناوب نصف شهري", image: "https://assets.conduire.ma/signs/alman3/sign_p1_46.png" },
    { name: "ممنوع الوقوف من 16 إلى 31", image: "https://assets.conduire.ma/signs/alman3/sign_p1_47.png" },
    { name: "قف - حاجز الشرطة", image: "https://assets.conduire.ma/signs/alman3/sign_p1_48.png" },
    { name: "ممنوع مرور العربات ذات المحرك", image: "https://assets.conduire.ma/signs/alman3/sign_p1_49.png" },
    { name: "نهاية تحديد السرعة في 60 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_50.png" },
    { name: "تحديد السرعة في 40 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p1_51.png" },
    { name: "ممنوع مرور القطعان", image: "https://assets.conduire.ma/signs/alman3/sign_p1_52.png" },
    { name: "نهاية منطقة تحديد السرعة 30", image: "https://assets.conduire.ma/signs/alman3/sign_p1_53.png" },
    { name: "نهاية منع مرور المتزلجين", image: "https://assets.conduire.ma/signs/alman3/sign_p1_54.png" },
  ] },
  { title: "علامات نهاية المنع", items: [
    { name: "ممنوع تغيير الاتجاه نحو اليسار", image: "https://assets.conduire.ma/signs/alman3/sign_p2_0.png" },
    { name: "نهاية منطقة الوقوف بالمقابل والوقت", image: "https://assets.conduire.ma/signs/alman3/sign_p2_1.png" },
    { name: "نهاية تحديد السرعة 80 كلم", image: "https://assets.conduire.ma/signs/alman3/sign_p2_2.png" },
    { name: "نهاية منع الوقوف بالتناوب الشهري", image: "https://assets.conduire.ma/signs/alman3/sign_p2_3.png" },
    { name: "نهاية منع الوقوف", image: "https://assets.conduire.ma/signs/alman3/sign_p2_4.png" },
    { name: "نهاية تحديد السرعة في 40", image: "https://assets.conduire.ma/signs/alman3/sign_p2_5.png" },
    { name: "ممنوع الوقوف بالتناوب نصف شهري", image: "https://assets.conduire.ma/signs/alman3/sign_p2_6.png" },
    { name: "نهاية منع الوقوف بالتناوب الشهري", image: "https://assets.conduire.ma/signs/alman3/sign_p2_7.png" },
    { name: "نهاية منع استعمال المنبه الصوتي", image: "https://assets.conduire.ma/signs/alman3/sign_p2_8.png" },
    { name: "ممنوع الوقوف", image: "https://assets.conduire.ma/signs/alman3/sign_p2_9.png" },
    { name: "نهاية جميع قيود المنع", image: "https://assets.conduire.ma/signs/alman3/sign_p2_10.png" },
    { name: "ممنوع مرور الدراجات", image: "https://assets.conduire.ma/signs/alman3/sign_p2_11.png" },
    { name: "دخول منطقة تحديد السرعة 30", image: "https://assets.conduire.ma/signs/alman3/sign_p2_12.png" },
    { name: "نهاية منطقة التوقف المؤدى عنه", image: "https://assets.conduire.ma/signs/alman3/sign_p2_13.png" },
    { name: "ممنوع مرور عربات نقل البضائع", image: "https://assets.conduire.ma/signs/alman3/sign_p2_14.png" },
    { name: "ممنوع المرور في الاتجاهين", image: "https://assets.conduire.ma/signs/alman3/sign_p2_15.png" },
  ] },
  { title: "علامات الإجبار", items: [
    { name: "إجبارية الانعطاف نحو اليمين", image: "https://assets.conduire.ma/signs/ijbar/image_0.png" },
    { name: "إجبارية الانعطاف نحو اليسار", image: "https://assets.conduire.ma/signs/ijbar/image_1.png" },
    { name: "إجبارية المرور من جهة اليسار", image: "https://assets.conduire.ma/signs/ijbar/image_2.png" },
    { name: "إجبارية المرور من اليمين", image: "https://assets.conduire.ma/signs/ijbar/image_3.png" },
    { name: "اتجاه إجباري إلى الأمام", image: "https://assets.conduire.ma/signs/ijbar/image_4.png" },
    { name: "اتجاه إجباري نحو اليمين", image: "https://assets.conduire.ma/signs/ijbar/image_5.png" },
    { name: "اتجاه إجباري نحو اليسار", image: "https://assets.conduire.ma/signs/ijbar/image_7.png" },
    { name: "إجبارية المتابعة للأمام أو اليمين", image: "https://assets.conduire.ma/signs/ijbar/image_8.png" },
    { name: "إجبارية المتابعة للأمام أو الانعطاف يسارا", image: "https://assets.conduire.ma/signs/ijbar/image_9.png" },
    { name: "إجبارية الانعطاف يمينا أو يسارا", image: "https://assets.conduire.ma/signs/ijbar/image_10.png" },
    { name: "اتجاه دوراني إجباري", image: "https://assets.conduire.ma/signs/ijbar/image_11.png" },
    { name: "ممر إجباري للدراجات", image: "https://assets.conduire.ma/signs/ijbar/image_12.png" },
    { name: "ممر إجباري للعربات المجرورة بالحيوانات", image: "https://assets.conduire.ma/signs/ijbar/image_13.png" },
    { name: "ممر إجباري للعربات اليدوية", image: "https://assets.conduire.ma/signs/ijbar/image_14.png" },
    { name: "ممر إجباري للحيوانات الأليفة", image: "https://assets.conduire.ma/signs/ijbar/image_15.png" },
    { name: "ممر إجباري للخيالة", image: "https://assets.conduire.ma/signs/ijbar/image_16.png" },
    { name: "إجبارية تغيير المسلك نحو اليمين", image: "https://assets.conduire.ma/signs/ijbar/image_17.png" },
    { name: "ممر إجباري للراجلين", image: "https://assets.conduire.ma/signs/ijbar/image_18.png" },
    { name: "السرعة الدنيا الإجبارية 30 كلم", image: "https://assets.conduire.ma/signs/ijbar/image_19.png" },
    { name: "ممر إجباري للحافلات", image: "https://assets.conduire.ma/signs/ijbar/image_20.png" },
    { name: "إجبارية استعمال سلاسل الثلوج", image: "https://assets.conduire.ma/signs/ijbar/image_21.png" },
    { name: "إجبارية تشغيل أضواء التقابل", image: "https://assets.conduire.ma/signs/ijbar/image_22.png" },
    { name: "مسلك إجباري للترامواي", image: "https://assets.conduire.ma/signs/ijbar/image_23.png" },
    { name: "مسلك إجباري للمركبات البطيئة", image: "https://assets.conduire.ma/signs/ijbar/image_24.png" },
  ] },
  { title: "علامات نهاية الإجبار", items: [
    { name: "نهاية السرعة الدنيا الإجبارية 40", image: "https://assets.conduire.ma/signs/ijbar/image_25.png" },
    { name: "نهاية الممر الإجباري للدراجات", image: "https://assets.conduire.ma/signs/ijbar/image_26.png" },
    { name: "نهاية الممر الإجباري للراجلين", image: "https://assets.conduire.ma/signs/ijbar/image_27.png" },
    { name: "نهاية الممر الإجباري للخيالة", image: "https://assets.conduire.ma/signs/ijbar/image_28.png" },
    { name: "نهاية الممر الإجباري للحافلات", image: "https://assets.conduire.ma/signs/ijbar/image_29.png" },
    { name: "نهاية إجبارية استعمال سلاسل الثلوج", image: "https://assets.conduire.ma/signs/ijbar/image_30.png" },
    { name: "نهاية إجبارية إشعال الأضواء", image: "https://assets.conduire.ma/signs/ijbar/image_31.png" },
    { name: "نهاية المسلك الإجباري للترامواي", image: "https://assets.conduire.ma/signs/ijbar/image_32.png" },
    { name: "نهاية المسلك الإجباري للعربات البطيئة", image: "https://assets.conduire.ma/signs/ijbar/image_33.png" },
  ] },
  { title: "علامات إضافية", items: [
    { name: "رقم الطريق الوطنية 2", image: "https://assets.conduire.ma/signs/mawaqi3/image_0.png" },
    { name: "رقم طريق جهوية 312", image: "https://assets.conduire.ma/signs/mawaqi3/image_1.png" },
    { name: "رقم طريق إقليمية 5311", image: "https://assets.conduire.ma/signs/mawaqi3/image_2.png" },
    { name: "رقم طريق غابوية 16", image: "https://assets.conduire.ma/signs/mawaqi3/image_3.png" },
    { name: "دخول تجمع عمراني شفشاون", image: "https://assets.conduire.ma/signs/mawaqi3/image_4.png" },
    { name: "نهاية التجمع العمراني شفشاون", image: "https://assets.conduire.ma/signs/mawaqi3/image_5.png" },
    { name: "علامة دخول مدينة طانطان", image: "https://assets.conduire.ma/signs/mawaqi3/image_6.png" },
    { name: "نهاية التجمع العمراني طانطان", image: "https://assets.conduire.ma/signs/mawaqi3/image_7.png" },
    { name: "علامة تحديد الموقع أقشور", image: "https://assets.conduire.ma/signs/mawaqi3/image_9.png" },
    { name: "علامة تحديد موقع مجرى مائي", image: "https://assets.conduire.ma/signs/mawaqi3/image_10.png" },
    { name: "باحة الاستراحة الخميسات", image: "https://assets.conduire.ma/signs/mawaqi3/image_11.png" },
    { name: "علامة اسم الشارع", image: "https://assets.conduire.ma/signs/mawaqi3/image_12.png" },
    { name: "مخرج إغاثة على اليمين 100 متر", image: "https://assets.conduire.ma/signs/mawaqi3/image_13.png" },
    { name: "مخرج إغاثة لليسار على بعد 200 متر", image: "https://assets.conduire.ma/signs/mawaqi3/image_14.png" },
    { name: "نهاية باحة الاستراحة بالخميسات", image: "https://assets.conduire.ma/signs/mawaqi3/image_15.png" },
  ] },
  { title: "الصوى وعلامات المسافة", items: [
    { name: "صوة كيلومترية للطريق الوطنية", image: "https://assets.conduire.ma/signs/mawaqi3/image_16.png" },
    { name: "صوة حدود الإقليم على طريق وطنية", image: "https://assets.conduire.ma/signs/mawaqi3/image_17.png" },
    { name: "صوة كيلومترية للطريق الجهوية", image: "https://assets.conduire.ma/signs/mawaqi3/image_18.png" },
    { name: "صوة كيلومترية للطريق الإقليمية", image: "https://assets.conduire.ma/signs/mawaqi3/image_19.png" },
    { name: "علامة التموقع الكيلومتري بالطريق السيار A2", image: "https://assets.conduire.ma/signs/mawaqi3/image_20.png" },
    { name: "صوة هيكتومترية رقم 9", image: "https://assets.conduire.ma/signs/mawaqi3/image_21.png" },
    { name: "صفيحة تحديد النقط الكيلومترية", image: "https://assets.conduire.ma/signs/mawaqi3/image_22.png" },
  ] },
  { title: "علامات التنشيط السياحي وذات النفع المحلي", items: [
    { name: "موقع أثري وليلي", image: "https://assets.conduire.ma/signs/mawaqi3/image_23.png" },
    { name: "موقع تاريخي أو أثري", image: "https://assets.conduire.ma/signs/mawaqi3/image_24.png" },
    { name: "موقع أثري وليلي", image: "https://assets.conduire.ma/signs/mawaqi3/image_25.png" },
    { name: "علامة مدار توبقال السياحي", image: "https://assets.conduire.ma/signs/mawaqi3/image_26.png" },
    { name: "المنتزه الوطني توبقال", image: "https://assets.conduire.ma/signs/mawaqi3/image_27.png" },
    { name: "إشارة سياحية قصبة أيت حدو", image: "https://assets.conduire.ma/signs/mawaqi3/image_28.png" },
    { name: "نهاية المنتزه الوطني تالاسمطان", image: "https://assets.conduire.ma/signs/mawaqi3/image_30.png" },
    { name: "توجيه لموقع سياحي ساحة جامع الفنا", image: "https://assets.conduire.ma/signs/mawaqi3/image_31.png" },
    { name: "موقع سياحي تاريخي وليلي", image: "https://assets.conduire.ma/signs/mawaqi3/image_32.png" },
    { name: "موقع سياحي وليلي", image: "https://assets.conduire.ma/signs/mawaqi3/image_33.png" },
    { name: "موقع تاريخي قصبة آيت حدو", image: "https://assets.conduire.ma/signs/mawaqi3/image_34.png" },
  ] },
  { title: "علامات للدلالة على موقع خط", items: [
    { name: "أعمدة تحديد المسافات والمنعرجات", image: "https://assets.conduire.ma/signs/mawaqi3/image_35.png" },
    { name: "صوة ملتقى الطرق", image: "https://assets.conduire.ma/signs/mawaqi3/image_36.png" },
    { name: "جهاز تعزيز التشوير الدائم", image: "https://assets.conduire.ma/signs/mawaqi3/image_37.png" },
    { name: "صوة زرقاء لتعزيز التشوير", image: "https://assets.conduire.ma/signs/mawaqi3/image_38.png" },
    { name: "أرمة تحديد حافة الطريق", image: "https://assets.conduire.ma/signs/mawaqi3/image_39.png" },
    { name: "صوة منعرج خطير لليمين", image: "https://assets.conduire.ma/signs/mawaqi3/image_40.png" },
    { name: "إجبارية المرور من جهة اليمين", image: "https://assets.conduire.ma/signs/mawaqi3/image_41.png" },
    { name: "صوة للإشارة إلى تباعد المسالك", image: "https://assets.conduire.ma/signs/mawaqi3/image_43.png" },
    { name: "صوى تحديد منعرج", image: "https://assets.conduire.ma/signs/mawaqi3/image_44.png" },
    { name: "مؤشر اتجاه الرياح", image: "https://assets.conduire.ma/signs/mawaqi3/image_45.png" },
    { name: "صوة لتحديد تباعد المسالك", image: "https://assets.conduire.ma/signs/mawaqi3/image_46.png" },
    { name: "أعمدة الاقتراب من سكة حديدية", image: "https://assets.conduire.ma/signs/mawaqi3/image_47.png" },
    { name: "خطر تيار كهربائي عالي الضغط", image: "https://assets.conduire.ma/signs/mawaqi3/image_48.png" },
    { name: "موقع سكة حديدية بدون حواجز", image: "https://assets.conduire.ma/signs/mawaqi3/image_49.png" },
  ] },
];
